substitutions:
  name: prusa-mk4-smart-enclosure
  friendly_name: Prusa MK4 smart enclosure
  api_encryption_key: "add your encryption key here"
  ota_password: "add your OTA password here"
  frame_rate_buffer_size: "10"
  resolution: 640x480
  fan_speed_steps: "3"
  fan_minimum_speed_duty_cycle: "0.2"
  idle_framerate: "0.1"
  automatic_camera_light_framerate: "0.5"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  on_boot:
    priority: 300
    then:
      - script.execute: enable_automatic_filtration
      - script.execute: evaluate_automatic_lighting
    
esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3 
  framework:
    type: arduino
    version: 2.0.8
    platform_version: 6.2.0

psram:
  mode: octal
  speed: 120MHz

external_components:
  - source:
      type: git
      url: https://github.com/Rudd-O/esphome_freenove_camera_component
    components:
      - esp32_camera
  # Optionally comment the following block out if you are not using the
  # optional BME688 sensor.  Keep the following two lines uncommented otherwise.
  - source: github://neffs/esphome@bsec2_bme68x
    components: [ bme68x_bsec2_i2c ]

# Enable logging
logger:
  # Change me from debug to info when everything has been tested to work correctly.
  level: debug
  logs:
    pulse_counter: info
    sensor: info
    fan.automatic: info
    text_sensor: info

# Enable Home Assistant API.
# Comment this whole block if not using Home Assistant.
api:
  encryption:
    key: "$api_encryption_key"
  # Comment the following line after pairing with Home Assistant.
  # Leave it uncommented if you plan to use only the ESP32 Web server
  # integration below.
  reboot_timeout: 0s

ota:
  password: "$ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # You may want to enable the next section if the ESP32 device is
  # not connecting to your Wi-Fi network after flashing for the
  # first time.  Re-flash after enabling.
  # Docs at https://esphome.io/components/wifi.html#access-point-mode
  # ap: {}

# Leave this block uncomemented for initial testing.
# Later on, comment this block if you will only be using Home Assistant
# to control your smart enclosure.  Leave it uncommented if you plan to
# control your smart enclosure through the ESP32 Web server.
# Reflash via Wi-Fi after that change.
web_server:
  port: 80
  include_internal: true
  local: true

# Leave this block uncommented for initial testing.
# Later on, comment this block if you will only be using the camera
# through Home Assistant instead of streaming MJPEG to Frigate or
# another NVR solution.  Reflash via Wi-Fi after that change.
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

globals:
  - id: last_update_times
    type: unsigned int[$frame_rate_buffer_size]
    restore_value: no

script:
  - id: enable_automatic_filtration
    then:
      - lambda: |
          auto call = id(advanced_filtration_system).make_call();
          call.set_preset_mode("automatic");
          call.perform();
      - script.execute: evaluate_automatic_filtration
  - id: evaluate_automatic_filtration
    then:
      - lambda: |
          if (id(advanced_filtration_system).preset_mode == "automatic") {
            // Q: Why do we use static IAQ?
            // A: https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/Explanation-on-static-IAQ-breath-VOC-and-CO2-equivalent/m-p/7536/highlight/true#M483
            float iaq_ = float(id(static_iaq).state);
            if (iaq_ == -2.0) {
              auto printer_printing = !(id(printer).state == "finished" || id(printer).state == "idle" || id(printer).state == "unknown");
              if (
                  !printer_printing
                  &&
                  id(advanced_filtration_system).state
                ) {
                ESP_LOGD("fan.automatic", "Turning off fan based on printer state");
                auto call = id(advanced_filtration_system).make_call();
                call.set_preset_mode("automatic"); // Copy preset mode into call so it won't get cleared
                call.set_state(false);
                call.perform();
              } else if (
                printer_printing
                &&
                !id(advanced_filtration_system).state
              ) {
                ESP_LOGD("fan.automatic", "Setting fan to maximum speed because the printer is %s", id(printer).state.c_str());
                auto call = id(advanced_filtration_system).make_call();
                call.set_preset_mode("automatic"); // Copy preset mode into call so it won't get cleared
                call.set_speed($fan_speed_steps);
                call.set_state(true);
                call.perform();
              }
            } else {
              float max_iaq = float(id(maximum_automatic_filtration).state);
              float min_iaq = float(id(minimum_automatic_filtration).state);
              int speed_we_want = int(ceil((iaq_ - min_iaq) / (max_iaq - min_iaq) * ($fan_speed_steps - 1)));
              if (speed_we_want > $fan_speed_steps) speed_we_want = $fan_speed_steps;
              if (speed_we_want < 0) speed_we_want = 0;
              ESP_LOGD("fan.automatic", "IAQ %.1f / max %.1f / min %.1f / target_speed %d", iaq_, max_iaq, min_iaq, speed_we_want);
              if (speed_we_want == 0 && id(advanced_filtration_system).state) {
                ESP_LOGD("fan.automatic", "Turning off fan");
                auto call = id(advanced_filtration_system).make_call();
                call.set_preset_mode("automatic"); // Copy preset mode into call so it won't get cleared
                call.set_state(false);
                call.perform();
              } else if (speed_we_want > 0 && (!id(advanced_filtration_system).state || id(advanced_filtration_system).speed != speed_we_want)) {
                ESP_LOGD("fan.automatic", "Setting fan to speed %d", speed_we_want);
                auto call = id(advanced_filtration_system).make_call();
                call.set_preset_mode("automatic"); // Copy preset mode into call so it won't get cleared
                call.set_speed(speed_we_want);
                call.set_state(true);
                call.perform();
              }
            }
          }
  - id: evaluate_automatic_lighting
    then:
      - lambda: |
          if (id(automatic_camera_light).state) {
            auto framerate = float(id(camera_frame_rate).state);
            if (framerate >= $automatic_camera_light_framerate && !id(camera_light).current_values.is_on()) {
              ESP_LOGD("light.automatic", "Turning on light based on camera state");
              auto call = id(camera_light).turn_on();
              call.perform();
            } else if (framerate < $automatic_camera_light_framerate && id(camera_light).current_values.is_on()) {
              ESP_LOGD("light.automatic", "Turning off light based on camera state");
              auto call = id(camera_light).turn_off();
              call.perform();
            }
          }

# Comment the following block out if you are not using any I2C sensor.
i2c:
  sda: GPIO40
  scl: GPIO39
# Comment the following line if you are not using the BME688 sensor,
# keep it uncommented if you are.
  frequency: 400kHz

# Keep the following block uncommented if you are using the BME688 sensor.
# Comment it if you are not.
bme68x_bsec2_i2c:
  model: bme688
  state_save_interval: 30min

esp32_camera:
  name: Camera
  id: camera
  framebuffer_in_psram: true
  external_clock:
    pin: GPIO15
    frequency: 40MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  idle_framerate: "$idle_framerate fps"
  max_framerate: 15 fps
  resolution: $resolution
  horizontal_mirror: false
  on_image:
    - component.update: camera_frame_rate

number:
  - platform: template
    name: Maximum automatic filtration
    id: maximum_automatic_filtration
    icon: mdi:fan-plus
    optimistic: true
    entity_category: config
    unit_of_measurement: IAQ
    step: 10
    min_value: 0
    max_value: 500
    restore_value: true
    initial_value: 200
    on_value:
      then:
        - script.execute: evaluate_automatic_filtration
  - platform: template
    name: Minimum automatic filtration
    id: minimum_automatic_filtration
    icon: mdi:fan-minus
    optimistic: true
    entity_category: config
    unit_of_measurement: IAQ
    step: 10
    min_value: 0
    max_value: 500
    restore_value: true
    initial_value: 100
    on_value:
      then:
        - script.execute: evaluate_automatic_filtration
  # Uncomment the next block if you are not using a sensor that provides an
  # IAQ index with ID `static_iaq`.  Leave it commented if you are using such a
  # sensor (e.g. the optional BME688 suggested by this project).
  # - platform: template
  #   optimistic: true
  #   internal: true
  #   name: Static IAQ
  #   id: static_iaq
  #   restore_value: no
  #   min_value: -2
  #   initial_value: -2
  #   step: 1
  #   max_value: 1

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
    icon: mdi:restart
  - platform: safe_mode
    name: Safe mode restart
    entity_category: diagnostic
    icon: mdi:restart-alert

# Could be useful to diagnose problems.
# debug:
#   update_interval: 5s

sensor:
# Could be useful to diagnose problems.
# - platform: debug
#   loop_time:
#     disabled_by_default: true
#     name: "Loop time"
#   psram:
#     disabled_by_default: true
#     name: "Free PSRAM"

- platform: template
  name: "Camera frame rate"
  id: camera_frame_rate
  lambda: |-
    float now = millis();
    unsigned int max_ = $frame_rate_buffer_size;
    unsigned int i;
    for (i = max_ - 1; i > 0; i--) {
      id(last_update_times)[i] = id(last_update_times)[i-1];
    }
    id(last_update_times)[0] = now;
    float avgdiff = 0.0;
    float mostrecentmillis = id(last_update_times)[0];
    for (i = 1; i < max_; i++) {
      if (mostrecentmillis == 0) {
        ESP_LOGD("framerate", "No more updates, breaking at %u", i);
        break;
      }
      avgdiff = mostrecentmillis - id(last_update_times)[i];
      if ((id(last_update_times)[i-1] - id(last_update_times)[i]) > 9500) {
        ESP_LOGD("framerate", "Big diff, breaking at %u", i);
        if (i > 1) {
          // This is at least value number three from most
          // recent to least recent.  Undo its use.
          i = i - 1;
          avgdiff = mostrecentmillis - id(last_update_times)[i];
          ESP_LOGD("framerate", "Compensating avgdiff");
        }
        break;
      }
    }
    if (avgdiff == 0.0) {
      return {};
    } else {
      avgdiff = avgdiff / i;
      float rate = 1000.0 / avgdiff;
      //if (rate >= 5.0) {
      //  rate = floor(rate + 0.5);
      //} else {
      //  rate = floor(rate * 10 + 0.5) / 10;
      //}
      return rate;
    }
  update_interval: never
  entity_category: diagnostic
  state_class: measurement
  device_class: frequency
  disabled_by_default: true
  filters:
    - delta: 20%
  on_value:
    - script.execute: evaluate_automatic_lighting

- platform: pulse_counter
  pin:
    number: GPIO14
    mode:
      input: true
  name: "Advanced filtration system fan speed"
  unit_of_measurement: RPM
  update_interval: 2s
  count_mode:
    rising_edge: DISABLE
    falling_edge: INCREMENT
  accuracy_decimals: 0
  filters:
    - multiply: 0.5
    - round: 0
    - delta: 20

- platform: uptime
  name: "Uptime"
  entity_category: diagnostic
- platform: wifi_signal
  name: "Wi-Fi signal strength"
  update_interval: 10s
  entity_category: "diagnostic"
- platform: internal_temperature
  name: "Device temperature"
  update_interval: 10s
  entity_category: "diagnostic"

# Keep the following block uncommented if you are using the BME688 sensor
# with the BSEC driver (the default).  Comment it if you are using any
# other sensor, or no sensor at all.
- platform: bme68x_bsec2_i2c
  temperature:
    name: "Temperature"
    filters:
      - median
  pressure:
    name: "Pressure"
    filters:
      - median
  humidity:
    name: "Humidity"
    filters:
      - median
  iaq:
    name: "IAQ"
    id: iaq
    filters:
      - median
    on_value:
      - component.update: iaq_classification
  iaq_static:
    name: "Static IAQ"
    id: static_iaq
    filters:
      - median
    on_value:
      - component.update: static_iaq_classification
      - script.execute: evaluate_automatic_filtration
  co2_equivalent:
    name: "CO2 equivalent"
    filters:
      - median
  breath_voc_equivalent:
    name: "Breath VOC equivalent"
    filters:
      - median
  gas_resistance:
    # Gas resistance in Ω
    name: "Gas resistance"
    entity_category: diagnostic
    filters:
      - median

switch:
  - platform: template
    name: Automatic camera light
    id: automatic_camera_light
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    icon: mdi:lightbulb-auto
    entity_category: config
    internal: false
    on_turn_on:
      then:
        - logger.log: "Automatic camera light turned on"
        - script.execute: evaluate_automatic_lighting
    on_turn_off:
      then:
        - logger.log: "Automatic camera light turned off"

binary_sensor:
  - platform: gpio
    icon: mdi:button-pointer
    disabled_by_default: true
    internal: false
    pin:
      number: GPIO43
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Camera light switch"
    on_multi_click:
      - timing:
          - ON for at most 0.5s
        then:
          - logger.log: "Camera light switch pressed"
          - if:
              condition:
                switch.is_on: automatic_camera_light
              then:
                - switch.turn_off: automatic_camera_light
          - light.toggle: camera_light
      - timing:
          - ON for at least 0.501s
        then:
          - logger.log: "Camera light switch long-pressed"
          - light.control:
              id: camera_light
              state: off
          - delay: 100ms
          - light.control:
              id: camera_light
              state: on
          - delay: 100ms
          - light.control:
              id: camera_light
              state: off
          - delay: 100ms
          - light.control:
              id: camera_light
              state: on
          - delay: 100ms
          - switch.turn_on: automatic_camera_light
  - platform: gpio
    icon: mdi:button-pointer
    disabled_by_default: true
    internal: true
    pin:
      number: GPIO44
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Advanced filtration system switch"
    on_multi_click:
      - timing:
          - ON for at most 0.5s
        then:
          - logger.log: "Automatic filtration system switch pressed"
          - fan.cycle_speed: advanced_filtration_system
      - timing:
          - ON for at least 0.501s
        then:
          - logger.log: "Automatic filtration system switch long-pressed"
          - script.execute: enable_automatic_filtration

output:
  - platform: gpio
    pin: GPIO47
    id: "out_1"
  - platform: ledc
    frequency: 19531Hz
    pin: GPIO21
    id: "out_2"
    channel: 2
  - platform: template
    id: fan_output_preprocessed
    type: float
    write_action:
      - lambda: |
          auto min_real_speed = $fan_minimum_speed_duty_cycle;
          auto min_speed_sent_by_speed_fan = 1.0 / $fan_speed_steps;
          auto max_speed = 1.0;
          auto compensated = min_real_speed + ((max_speed - min_real_speed) / (max_speed - min_speed_sent_by_speed_fan)) * (state - min_speed_sent_by_speed_fan);
          if (compensated < 0.0) {
            compensated = 0.0;
          }
          ESP_LOGD("stuff", "raw output is %.2f", state);
          ESP_LOGD("stuff", "compensated output is %.2f", compensated);
          id(out_2).write_state(compensated);

light:
  - platform: binary
    name: Camera light
    id: camera_light
    restore_mode: RESTORE_DEFAULT_OFF
    output: out_1
    icon: mdi:led-strip-variant

fan:
  - platform: speed
    name: Advanced filtration system
    id: advanced_filtration_system
    restore_mode: RESTORE_DEFAULT_OFF
    output: fan_output_preprocessed
    icon: mdi:air-filter
    speed_count: $fan_speed_steps
    preset_modes:
      - automatic
    on_preset_set:
      then:
        - if:
            condition:
              lambda: |
                return x == "automatic";
            then:
              - script.execute: evaluate_automatic_filtration

text_sensor:
  # Comment the following block out if you are not using the optional BME688 sensor,
  # keep it uncommented if you are using the BME688 sensor.
  - platform: template
    name: "IAQ classification"
    id: iaq_classification
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      auto iaq_ = int(id(iaq).state);
      if (iaq_ < 0) {
        // No IAQ sensor.
        return {"unknown"};
      }
      if (iaq_ <= 50) {
        return {"excellent"};
      }
      else if (iaq_ <= 100) {
        return {"good"};
      }
      else if (iaq_ <= 150) {
        return {"lightly polluted"};
      }
      else if (iaq_ <= 200) {
        return {"moderately polluted"};
      }
      else if (iaq_ <= 250) {
        return {"heavily polluted"};
      }
      else if (iaq_ <= 350) {
        return {"severely polluted"};
      }
      else if (iaq_ <= 500) {
        return {"extremely polluted"};
      }
      else {
        // ESP_LOGD("iaq-classification", "IAQ not yet established: %s", id(static_iaq).state);
        return {"unknown"};
      }
    update_interval: never

  - platform: template
    name: "Static IAQ classification"
    id: static_iaq_classification
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      auto iaq_ = int(id(static_iaq).state);
      if (iaq_ < 0) {
        // No IAQ sensor.
        return {"unknown"};
      }
      if (iaq_ <= 50) {
        return {"excellent"};
      }
      else if (iaq_ <= 100) {
        return {"good"};
      }
      else if (iaq_ <= 150) {
        return {"lightly polluted"};
      }
      else if (iaq_ <= 200) {
        return {"moderately polluted"};
      }
      else if (iaq_ <= 250) {
        return {"heavily polluted"};
      }
      else if (iaq_ <= 350) {
        return {"severely polluted"};
      }
      else if (iaq_ <= 500) {
        return {"extremely polluted"};
      }
      else {
        // ESP_LOGD("iaq-classification", "IAQ not yet established: %s", id(static_iaq).state);
        return {"unknown"};
      }
    update_interval: never

  # Comment the following block out if you are not using the optional BME688 sensor,
  # keep it uncommented if you are using the BME688 sensor.
  - platform: bme68x_bsec2_i2c
    iaq_accuracy: 
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "IAQ accuracy"

  # Uncomment and fill in your Home Assistant 3D printer entity ID,
  # if you don't have a sensor that supports IAQ via the `static_iaq`
  # ID, but you do have a printer sensor that reflects printer state,
  # in order to enable automatic filtration based on when the printer
  # is printing.
  # Keep commented otherwise.
  # - platform: homeassistant
  #   name: "Printer"
  #   id: printer
  #   entity_id: sensor.prusa_mk4
  #   internal: true
  #   on_value:
  #     then:
  #       - script.execute: evaluate_automatic_filtration
  # Keep uncommented if you have a sensor that supports IAQ via the
  # `static_iaq` ID, or you don't have a have a sensor for your 3D
  # printer that changes based on whether the printer is printing or not.
  - platform: template
    lambda: |
      return {"unknown"};
    id: printer
    internal: true
    on_value:
      then:
        - script.execute: evaluate_automatic_filtration
